# Generated by Django 5.1.2 on 2024-10-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezume',
            old_name='rezume_name',
            new_name='rezume_description',
        ),
    ]
