# Generated by Django 5.1.2 on 2024-11-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rezume_name_rezume_rezume_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezume',
            old_name='rezume_description',
            new_name='description',
        ),
    ]
