# Generated by Django 5.1.2 on 2024-11-13 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('a', 'Active'), ('d', 'Deleted')], default='a', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Rezume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('dr', 'Draft'), ('del', 'Deleted'), ('f', 'Formed'), ('c', 'Completed'), ('r', 'Rejected')], default='dr', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rezumes', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_rezumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RezumeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('rezume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rezume')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rezume',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('creator',), name='unique_draft_per_user'),
        ),
        migrations.AddConstraint(
            model_name='rezumejob',
            constraint=models.UniqueConstraint(fields=('rezume', 'job'), name='unique_rezume_job'),
        ),
    ]
