# Generated by Django 5.1.2 on 2025-02-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezume',
            name='review',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
