# Generated by Django 5.1.2 on 2024-12-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezumejob',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
