# Generated by Django 5.1.2 on 2025-02-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rezume_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezume',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
